### PR TITLE
Add "HTML To Markdown" project

### PR DESCRIPTION
**Pull request by colinodell**
A couple notes:

* Website is currently pointing to GitHub; I'll update that once I get the `gh-pages` up and running.  This may take a few days.
* I only translated the description into Spanish, since I know it well enough to be sure the translation is accurate.  I can certainly auto-translate into the other languages if desired - just let me know.

### CODE REVIEW

**Comment by frankdejonge** [comment]
Looks good to me, I'll let others get the chance to get their two cents in. If nothing pops up I'll merge it.

**Comment by colinodell** [comment]
Perfect, thanks!

**Comment by reinink** [comment]
I think it makes sense to just do what you did, and put English in for the other languages. Our language maintainers periodically review and update these. Looks good to me!

**Comment by frankdejonge** [comment]
@colinodell merged :)

**Comment by colinodell** [comment]
Thanks @frankdejonge! :)

**Pull request merged**
