### PR TITLE
Updated the factory muffin maintainer

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This probably needs updating in the other language data files too.

### CODE REVIEW

**Comment by frankdejonge** [comment]
@GrahamCampbell this probably needs to be updated in all the language files.

**Comment by frankdejonge** [comment]
@GrahamCampbell could you include those changes in this PR too?

**Comment by GrahamCampbell** [comment]
Yeh, sure. I'll just need to clone the repo instead of being lazy and doing it from the web. ;)

**Comment by frankdejonge** [comment]
Hehe, web edits. Gotta love them.

**Comment by GrahamCampbell** [comment]
Done. :)

**Pull request merged**
