### PR TITLE
Packages/URI: Update "URL" to "URI"

### PR DESCRIPTION
**Pull request by hansott**
Does this change makes sense?

### CODE REVIEW

**Comment by hansott** [comment]
See https://github.com/thephpleague/url/pull/95#issuecomment-172479091

**Comment by nyamsprod** [comment]
This change will be made when every pieces are put in place and validated. We need to move the documentation and set up the subdomain first before thinking of applying this change. This will be done when I have the time

**Comment by nyamsprod** [comment]
@hansott This PR can be closed has the issue has been resolved in another PR

**Comment by hansott** [comment]
:+1:

**Pull request closed without merging**
