### PR TITLE
Adding league/uri information

### PR DESCRIPTION
**Pull request by nyamsprod**
Separation between league\url and league\uri

### CODE REVIEW

**Comment by reinink** [comment]
To be clear, you're keeping both packages active?

**Comment by nyamsprod** [comment]
league URL is EOL as stated but since september people are still downloading it ... it there was a way to mark it as deprecated on the main league package I would.
Hence I think that package like Concrete5 are still relying on league url so removing it completely would not be responsible.

**Comment by nyamsprod** [comment]
I've added the following phrase on the url.thephpleague.com website on each pages

> League\Url is not unsupported anymore. We strongly encourage you to upgrade your code and use instead League\Uri.

But I already know that this is not enough

**Comment by reinink** [comment]
Right. We should probably figure out a way to show that the URL package is deprecated. But yeah, for now let's merge this in so people have access to the docs.

**Pull request merged**
